#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import os
from pathlib import Path
import re
import sys
import tempfile
import tomllib


ROOT = Path(__file__).resolve().parents[1]
SKILL_TEMPLATE = ROOT / "sources" / "pave-init" / "SKILL.md.tmpl"
ROLE_SOURCE_DIR = ROOT / "sources" / "roles"
BINDING_DIR = ROOT / "sources" / "bindings"
SCHEMA_PATH = BINDING_DIR / "schema.json"
EXPECTED_BINDING_FILES = {"claude.toml", "codex.toml"}
EXPECTED_ROLE_NAMES = {
    "forward-tester",
    "node-planner",
    "pave-material-reviewer",
    "research-delegate",
    "skill-builder",
    "system-explorer",
}
EXPECTED_SLOTS = {
    "FRONTMATTER",
    "PRODUCT_INTRO",
    "MULTI_AGENT_CONTRACT",
    "PACKAGE_IDENTITY",
    "MANIFEST_COMPONENT",
    "ROLE_COMPONENT",
    "HOOK_COMPONENT",
    "ROLE_RUNTIME_BINDING",
    "MODEL_RUNTIME_BINDING",
    "HOOK_RUNTIME_BINDING",
    "SCRIPT_RUNTIME_BINDING",
    "DELIVERY_INSTALL_BULLET",
    "SKILL_VALIDATION_BINDING",
}
EXPECTED_TOP_LEVEL = {
    "version",
    "harness",
    "skill_output",
    "agent_output_kind",
    "slots",
    "roles",
}
PLACEHOLDER = re.compile(r"\{\{([A-Z][A-Z0-9_]*)\}\}")
GENERATED_MARKER = "Generated by scripts/build_packages.py; source-sha256:"
EDIT_WARNING = "DO NOT EDIT. Change sources/ or bindings, then rebuild."
FORBIDDEN_SHARED_MECHANICS = (
    "claude code",
    "codex",
    ".claude-plugin",
    ".codex-plugin",
    "CLAUDE_",
    "AskUserQuestion",
    "SendMessage",
    "subagent_type",
    "run_in_background",
    "claude --plugin-dir",
    "claude -p",
    "pave-init:",
    "$pave-init",
    "$skill-creator",
    "skill-creator:",
    "Agent tool",
    "Workflow tool",
    "spawn_agent",
    "send_input",
    "followup_task",
    "wait_agent",
    "interrupt_agent",
    "fork_turns",
    "request_user_input",
    "codex exec",
    "pave_init_",
    "custom-agent TOML",
    "hooks/hooks.json",
    "PAVE_PLUGIN_ROOT",
    "sonnet",
    "opus",
    "fable",
)
HARNESS_SECTION = re.compile(
    r"<!--\s*harness-specific:(?:claude|codex):start\s*-->.*?"
    r"<!--\s*harness-specific:(?:claude|codex):end\s*-->",
    re.IGNORECASE | re.DOTALL,
)


class BuildError(RuntimeError):
    pass


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def read_utf8(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError as error:
        raise BuildError(f"{display_path(path)}: not valid UTF-8") from error


def validate_schema_value(value: object, schema: dict, location: str) -> None:
    expected_type = schema.get("type")
    type_matches = {
        "object": isinstance(value, dict),
        "string": isinstance(value, str),
        "integer": isinstance(value, int) and not isinstance(value, bool),
        "boolean": isinstance(value, bool),
    }
    if expected_type is not None and not type_matches.get(expected_type, False):
        raise BuildError(
            f"{location}: schema validation failed: expected {expected_type}"
        )
    if "const" in schema and value != schema["const"]:
        raise BuildError(
            f"{location}: schema validation failed: expected {schema['const']!r}"
        )
    if "enum" in schema and value not in schema["enum"]:
        raise BuildError(
            f"{location}: schema validation failed: expected one of {schema['enum']!r}"
        )
    if not isinstance(value, dict):
        return

    required = set(schema.get("required", []))
    missing = required - set(value)
    if missing:
        raise BuildError(
            f"{location}: schema validation failed: missing {sorted(missing)}"
        )
    minimum = schema.get("minProperties")
    if isinstance(minimum, int) and len(value) < minimum:
        raise BuildError(
            f"{location}: schema validation failed: needs at least {minimum} properties"
        )

    properties = schema.get("properties", {})
    additional = schema.get("additionalProperties", True)
    for key, item in value.items():
        item_location = f"{location}.{key}"
        if key in properties:
            validate_schema_value(item, properties[key], item_location)
        elif additional is False:
            raise BuildError(
                f"{location}: schema validation failed: unknown property {key!r}"
            )
        elif isinstance(additional, dict):
            validate_schema_value(item, additional, item_location)


def validate_schema_contract() -> dict:
    schema = json.loads(read_utf8(SCHEMA_PATH))
    if schema.get("additionalProperties") is not False:
        raise BuildError(f"{SCHEMA_PATH}: top-level additionalProperties must be false")
    if set(schema.get("required", [])) != EXPECTED_TOP_LEVEL:
        raise BuildError(f"{SCHEMA_PATH}: required keys differ from generator contract")
    slot_schema = schema.get("properties", {}).get("slots", {})
    if slot_schema.get("additionalProperties") is not False:
        raise BuildError(f"{SCHEMA_PATH}: slot additionalProperties must be false")
    if set(slot_schema.get("required", [])) != EXPECTED_SLOTS:
        raise BuildError(f"{SCHEMA_PATH}: slot keys differ from generator contract")
    slot_properties = slot_schema.get("properties", {})
    if set(slot_properties) != EXPECTED_SLOTS:
        raise BuildError(f"{SCHEMA_PATH}: slot properties differ from generator contract")
    if any(value != {"type": "string"} for value in slot_properties.values()):
        raise BuildError(f"{SCHEMA_PATH}: every slot must require a string")
    return schema


def shared_runtime_sources() -> list[Path]:
    paths = [SKILL_TEMPLATE, *sorted(ROLE_SOURCE_DIR.glob("*.md.tmpl"))]
    paths.extend(sorted((ROOT / "skills" / "pave-init" / "orchestration").glob("*.md")))
    references = ROOT / "skills" / "pave-init" / "references"
    paths.extend(sorted(references.glob("*.md")))
    return paths


def validate_shared_runtime_sources() -> None:
    findings: list[str] = []
    for path in shared_runtime_sources():
        raw = read_utf8(path)
        text = HARNESS_SECTION.sub("", raw)
        unmatched = re.findall(r"<!--\s*harness-specific:[^>]+-->", text, re.IGNORECASE)
        if unmatched:
            findings.append(f"{path.relative_to(ROOT)}: unmatched harness section marker")
        for token in FORBIDDEN_SHARED_MECHANICS:
            if token.lower() in text.lower():
                findings.append(f"{path.relative_to(ROOT)}: {token}")
    if findings:
        raise BuildError("harness mechanics remain in shared runtime sources: " + "; ".join(findings))


def load_binding(path: Path, schema: dict) -> dict:
    with path.open("rb") as handle:
        binding = tomllib.load(handle)
    validate_schema_value(binding, schema, display_path(path))
    unknown = set(binding) - EXPECTED_TOP_LEVEL
    missing = EXPECTED_TOP_LEVEL - set(binding)
    if unknown or missing:
        raise BuildError(f"{path}: unknown={sorted(unknown)} missing={sorted(missing)}")
    if binding["version"] != 1:
        raise BuildError(f"{path}: unsupported binding version {binding['version']!r}")
    if binding["harness"] != path.stem:
        raise BuildError(f"{path}: harness must match file name")
    if binding["agent_output_kind"] not in {"markdown", "toml"}:
        raise BuildError(f"{path}: invalid agent_output_kind")
    slots = binding["slots"]
    if set(slots) != EXPECTED_SLOTS:
        raise BuildError(
            f"{path}: binding slots differ: expected={sorted(EXPECTED_SLOTS)} "
            f"actual={sorted(slots)}"
        )
    return binding


def analyze_placeholders(text: str) -> tuple[set[str], list[int]]:
    matches = list(PLACEHOLDER.finditer(text))
    valid_open = {match.start() for match in matches}
    valid_close = {match.end() - 2 for match in matches}
    malformed: list[int] = []
    for marker, valid_positions in (("{{", valid_open), ("}}", valid_close)):
        offset = 0
        while True:
            position = text.find(marker, offset)
            if position < 0:
                break
            if position not in valid_positions:
                malformed.append(position)
            offset = position + 1
    return {match.group(1) for match in matches}, sorted(set(malformed))


def render_template(template: str, slots: dict[str, str], source: Path) -> str:
    used, malformed = analyze_placeholders(template)
    unknown = sorted(used - set(slots))
    missing = sorted(set(slots) - used)
    if malformed or unknown or missing:
        raise BuildError(
            f"{source}: invalid placeholders: malformed_offsets={malformed} "
            f"unknown={unknown} missing={missing}"
        )
    rendered = PLACEHOLDER.sub(lambda match: slots[match.group(1)].rstrip(), template)
    leftovers, malformed = analyze_placeholders(rendered)
    if leftovers or malformed:
        raise BuildError(
            f"{source}: unresolved placeholders: names={sorted(leftovers)} "
            f"malformed_offsets={malformed}"
        )
    return rendered.rstrip() + "\n"


def source_hash(*parts: str) -> str:
    digest = hashlib.sha256()
    for part in parts:
        digest.update(part.encode("utf-8"))
        digest.update(b"\0")
    return digest.hexdigest()


def add_markdown_marker(content: str, digest: str) -> str:
    boundary = content.find("\n---\n", 4)
    if boundary < 0:
        raise BuildError("generated Markdown has no closing frontmatter delimiter")
    insertion = boundary + len("\n---\n")
    marker = f"\n<!-- {EDIT_WARNING} {GENERATED_MARKER} {digest} -->\n"
    return content[:insertion] + marker + content[insertion:]


def parse_role(path: Path) -> tuple[dict[str, str], str]:
    text = read_utf8(path)
    placeholders, malformed = analyze_placeholders(text)
    if placeholders or malformed:
        raise BuildError(
            f"{path}: role templates do not accept placeholders or brace tokens: "
            f"names={sorted(placeholders)} malformed_offsets={malformed}"
        )
    if not text.startswith("---\n") or "\n---\n" not in text[4:]:
        raise BuildError(f"{path}: role source needs simple YAML frontmatter")
    frontmatter, body = text[4:].split("\n---\n", 1)
    fields: dict[str, str] = {}
    for line in frontmatter.splitlines():
        if not line.strip():
            continue
        key, separator, value = line.partition(":")
        if not separator or not value.strip():
            raise BuildError(f"{path}: unsupported frontmatter line {line!r}")
        fields[key.strip()] = value.strip()
    for required in ("name", "description"):
        if required not in fields:
            raise BuildError(f"{path}: missing {required}")
    return fields, body.strip() + "\n"


def codex_role_name(role_name: str) -> str:
    return f"pave-init:{role_name}"


def codex_role_filename(role_name: str) -> str:
    if role_name == "pave-material-reviewer":
        return "pave_init_material_reviewer.toml"
    return "pave_init_" + role_name.replace("-", "_") + ".toml"


def codex_role_preamble(role_name: str) -> str:
    shared = (
        "The parent brief must start with `PAVE_PLUGIN_ROOT: <absolute plugin root>`. "
        "Resolve every `references/...`, `schemas/...`, and `scripts/...` path under "
        "`<PAVE_PLUGIN_ROOT>/skills/pave-init/`. This TOML contains the complete role "
        "contract; do not load or translate a Claude role file at runtime.\n\n"
    )
    special = {
        "forward-tester": (
            "Use the Codex clean-room launch and installation mechanics stated in the "
            "contract below. Inherit the real session model and reasoning defaults.\n\n"
        ),
        "pave-material-reviewer": (
            "Stay on this exact thread for the life of the review gate. Return findings "
            "to the parent and re-check repairs against your own prior findings.\n\n"
        ),
        "skill-builder": (
            "Generate Codex plugin manifests, custom-agent TOML plus explicit installers, "
            "plugin-level hooks, and `codex_exec_script` bindings when the approved plan "
            "requires them. Preserve every approved graph boundary.\n\n"
        ),
    }
    return shared + special.get(role_name, "")


def render_roles(binding: dict) -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    role_settings = binding["roles"]
    sources = sorted(ROLE_SOURCE_DIR.glob("*.md.tmpl"))
    source_names = {path.name.removesuffix(".md.tmpl") for path in sources}
    if source_names != EXPECTED_ROLE_NAMES:
        raise BuildError(
            f"role source set differs: expected={sorted(EXPECTED_ROLE_NAMES)} "
            f"actual={sorted(source_names)}"
        )
    if set(role_settings) != source_names:
        raise BuildError(
            f"{binding['harness']}: role binding mismatch: "
            f"sources={sorted(source_names)} settings={sorted(role_settings)}"
        )
    for source in sources:
        role_name = source.name.removesuffix(".md.tmpl")
        fields, body = parse_role(source)
        if fields["name"] != role_name:
            raise BuildError(f"{source}: name does not match file")
        settings = role_settings[role_name]
        digest = source_hash(
            read_utf8(source),
            json.dumps(settings, sort_keys=True),
            binding["harness"],
        )
        runtime = settings.get("runtime")
        if not isinstance(runtime, str) or not runtime.strip():
            raise BuildError(f"{source}: role binding needs non-empty runtime text")
        if binding["agent_output_kind"] == "markdown":
            if set(settings) != {"effort", "model", "runtime", "sandbox_mode"}:
                raise BuildError(
                    f"{source}: Claude role settings must contain model, effort, runtime, and sandbox_mode"
                )
            for key in ("model", "effort"):
                if not isinstance(settings[key], str) or not settings[key]:
                    raise BuildError(f"{source}: Claude role {key} must be a string")
                if settings[key] != "inherit":
                    fields[key] = settings[key]
            frontmatter = "\n".join(
                f"{key}: {json.dumps(value, ensure_ascii=False)}"
                for key, value in fields.items()
            )
            output = add_markdown_marker(
                f"---\n{frontmatter}\n---\n\n{runtime.strip()}\n\n{body}",
                digest,
            )
            output_path = ROOT / "agents" / f"{role_name}.md"
        else:
            allowed = {"model", "reasoning_effort", "runtime", "sandbox_mode"}
            if set(settings) != allowed:
                raise BuildError(f"{source}: Codex role settings must be {sorted(allowed)}")
            name = codex_role_name(role_name)
            instructions = (
                codex_role_preamble(role_name)
                + runtime.strip()
                + "\n\n"
                + body
            )
            lines = [
                f"# {EDIT_WARNING} {GENERATED_MARKER} {digest}",
                f"name = {json.dumps(name)}",
                f"description = {json.dumps(fields['description'])}",
            ]
            if settings["model"] != "inherit":
                lines.append(f"model = {json.dumps(settings['model'])}")
            if settings["reasoning_effort"] != "inherit":
                lines.append(
                    "model_reasoning_effort = "
                    + json.dumps(settings["reasoning_effort"])
                )
            lines.extend(
                [
                    f"sandbox_mode = {json.dumps(settings['sandbox_mode'])}",
                    f"developer_instructions = {json.dumps(instructions)}",
                    "",
                ]
            )
            output = "\n".join(lines)
            output_path = ROOT / "codex" / "agents" / codex_role_filename(role_name)
        outputs[output_path] = output
    return outputs


def build_outputs() -> dict[Path, str]:
    schema = validate_schema_contract()
    validate_shared_runtime_sources()
    template = read_utf8(SKILL_TEMPLATE)
    outputs: dict[Path, str] = {}
    binding_paths = sorted(BINDING_DIR.glob("*.toml"))
    actual_binding_files = {path.name for path in binding_paths}
    if actual_binding_files != EXPECTED_BINDING_FILES:
        raise BuildError(
            f"binding files differ: expected={sorted(EXPECTED_BINDING_FILES)} "
            f"actual={sorted(actual_binding_files)}"
        )
    for binding_path in binding_paths:
        binding = load_binding(binding_path, schema)
        skill_path = ROOT / binding["skill_output"]
        if not skill_path.resolve().is_relative_to(ROOT.resolve()):
            raise BuildError(f"{binding_path}: output escapes repository")
        if skill_path in outputs:
            raise BuildError(f"duplicate generated output {skill_path}")
        rendered = render_template(template, binding["slots"], SKILL_TEMPLATE)
        digest = source_hash(template, read_utf8(binding_path))
        outputs[skill_path] = add_markdown_marker(rendered, digest)
        for path, content in render_roles(binding).items():
            if path in outputs:
                raise BuildError(f"duplicate generated output {path}")
            outputs[path] = content
    return outputs


def marked_generated_files() -> set[Path]:
    candidates = {
        ROOT / "skills" / "pave-init" / "SKILL.md",
        ROOT / "codex" / "skills" / "pave-init" / "SKILL.md",
        *(ROOT / "agents").glob("*.md"),
        *(ROOT / "codex" / "agents").glob("*.toml"),
    }
    marked: set[Path] = set()
    for path in candidates:
        if not path.is_file():
            continue
        if GENERATED_MARKER in read_utf8(path):
            marked.add(path)
    return marked


def check_outputs(outputs: dict[Path, str]) -> int:
    failures = 0
    for path, expected in outputs.items():
        actual = read_utf8(path) if path.exists() else ""
        if actual == expected:
            continue
        failures += 1
        relative = path.relative_to(ROOT)
        print(f"STALE {relative}", file=sys.stderr)
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=str(relative),
            tofile=f"generated/{relative}",
            lineterm="",
        )
        for line in diff:
            print(line, file=sys.stderr)
    for path in sorted(marked_generated_files() - set(outputs)):
        failures += 1
        print(f"ORPHAN {path.relative_to(ROOT)}", file=sys.stderr)
    return failures


def staged_output(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temp_name = tempfile.mkstemp(
        prefix=f".{path.name}.new.",
        dir=path.parent,
    )
    temp_path = Path(temp_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        temp_path.chmod(0o644)
        return temp_path
    except BaseException:
        temp_path.unlink(missing_ok=True)
        raise


def backup_path(path: Path) -> Path:
    descriptor, temp_name = tempfile.mkstemp(
        prefix=f".{path.name}.backup.",
        dir=path.parent,
    )
    os.close(descriptor)
    backup = Path(temp_name)
    backup.unlink()
    return backup


def write_outputs(outputs: dict[Path, str], force: bool) -> None:
    orphans = marked_generated_files() - set(outputs)
    if orphans:
        listed = ", ".join(str(path.relative_to(ROOT)) for path in sorted(orphans))
        raise BuildError(f"remove orphaned generated outputs before building: {listed}")
    conflicts = [
        path
        for path, content in outputs.items()
        if path.exists() and read_utf8(path) != content
    ]
    if conflicts and not force:
        listed = ", ".join(str(path.relative_to(ROOT)) for path in conflicts)
        raise BuildError(
            "refusing to overwrite generated files: "
            f"{listed}; inspect with --check, then rerun with --force"
        )
    staged: dict[Path, Path] = {}
    installed: list[tuple[Path, Path | None]] = []
    backups: set[Path] = set()
    try:
        for path, content in outputs.items():
            staged[path] = staged_output(path, content)

        for path in outputs:
            backup: Path | None = None
            if path.exists():
                backup = backup_path(path)
                os.replace(path, backup)
                backups.add(backup)
            installed.append((path, backup))
            os.replace(staged[path], path)
    except BaseException:
        rollback_errors: list[str] = []
        for path, backup in reversed(installed):
            try:
                path.unlink(missing_ok=True)
                if backup is not None:
                    os.replace(backup, path)
                    backups.discard(backup)
            except OSError as error:
                rollback_errors.append(f"{display_path(path)}: {error}")
        if rollback_errors:
            raise BuildError(
                "output transaction failed and rollback was incomplete: "
                + "; ".join(rollback_errors)
                + "; preserved backups: "
                + ", ".join(display_path(path) for path in sorted(backups))
            )
        raise
    finally:
        for temp_path in staged.values():
            temp_path.unlink(missing_ok=True)

    cleanup_errors: list[str] = []
    for backup in sorted(backups):
        try:
            backup.unlink()
        except OSError as error:
            cleanup_errors.append(f"{display_path(backup)}: {error}")
    if cleanup_errors:
        raise BuildError(
            "outputs were written, but backup cleanup was incomplete: "
            + "; ".join(cleanup_errors)
        )

    for path in outputs:
        print(path.relative_to(ROOT))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build native PAVE Init packages")
    parser.add_argument("--check", action="store_true", help="fail on stale outputs")
    parser.add_argument(
        "--force",
        action="store_true",
        help="replace stale generated outputs after reviewing --check",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        outputs = build_outputs()
        if args.check:
            return 1 if check_outputs(outputs) else 0
        write_outputs(outputs, args.force)
        return 0
    except (
        BuildError,
        OSError,
        UnicodeError,
        json.JSONDecodeError,
        tomllib.TOMLDecodeError,
    ) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
