#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import hashlib
import json
from pathlib import Path
import re
import sys
import tomllib


ROOT = Path(__file__).resolve().parents[1]
SKILL_TEMPLATE = ROOT / "sources" / "pave-init" / "SKILL.md.tmpl"
ROLE_SOURCE_DIR = ROOT / "sources" / "roles"
BINDING_DIR = ROOT / "sources" / "bindings"
SCHEMA_PATH = BINDING_DIR / "schema.json"
EXPECTED_BINDING_FILES = {"claude.toml", "codex.toml"}
EXPECTED_ROLE_NAMES = {
    "forward-tester",
    "node-planner",
    "pave-material-reviewer",
    "research-delegate",
    "skill-builder",
    "system-explorer",
}
EXPECTED_SLOTS = {
    "FRONTMATTER",
    "PRODUCT_INTRO",
    "MULTI_AGENT_CONTRACT",
    "PACKAGE_IDENTITY",
    "MANIFEST_COMPONENT",
    "ROLE_COMPONENT",
    "HOOK_COMPONENT",
    "ROLE_RUNTIME_BINDING",
    "HOOK_RUNTIME_BINDING",
    "SCRIPT_RUNTIME_BINDING",
    "DELIVERY_INSTALL_BULLET",
}
EXPECTED_TOP_LEVEL = {
    "version",
    "harness",
    "skill_output",
    "agent_output_kind",
    "slots",
    "roles",
}
PLACEHOLDER = re.compile(r"\{\{([A-Z][A-Z0-9_]*)\}\}")
GENERATED_MARKER = "Generated by scripts/build_packages.py; source-sha256:"
FORBIDDEN_SHARED_MECHANICS = (
    "claude code",
    "codex",
    ".claude-plugin",
    ".codex-plugin",
    "CLAUDE_",
    "AskUserQuestion",
    "SendMessage",
    "subagent_type",
    "run_in_background",
    "claude --plugin-dir",
    "claude -p",
    "pave-init:",
    "$pave-init",
    "Agent tool",
    "Workflow tool",
    "spawn_agent",
    "send_input",
    "request_user_input",
    "codex exec",
    "pave_init_",
    "custom-agent TOML",
    "hooks/hooks.json",
    "PAVE_PLUGIN_ROOT",
    "sonnet",
    "opus",
    "fable",
)
HARNESS_SECTION = re.compile(
    r"<!--\s*harness-specific:(?:claude|codex):start\s*-->.*?"
    r"<!--\s*harness-specific:(?:claude|codex):end\s*-->",
    re.IGNORECASE | re.DOTALL,
)


class BuildError(RuntimeError):
    pass


def validate_schema_contract() -> None:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    if schema.get("additionalProperties") is not False:
        raise BuildError(f"{SCHEMA_PATH}: top-level additionalProperties must be false")
    if set(schema.get("required", [])) != EXPECTED_TOP_LEVEL:
        raise BuildError(f"{SCHEMA_PATH}: required keys differ from generator contract")
    slot_schema = schema.get("properties", {}).get("slots", {})
    if slot_schema.get("additionalProperties") is not False:
        raise BuildError(f"{SCHEMA_PATH}: slot additionalProperties must be false")
    if set(slot_schema.get("required", [])) != EXPECTED_SLOTS:
        raise BuildError(f"{SCHEMA_PATH}: slot keys differ from generator contract")


def shared_runtime_sources() -> list[Path]:
    paths = [SKILL_TEMPLATE, *sorted(ROLE_SOURCE_DIR.glob("*.md.tmpl"))]
    paths.extend(sorted((ROOT / "skills" / "pave-init" / "orchestration").glob("*.md")))
    references = ROOT / "skills" / "pave-init" / "references"
    paths.extend(sorted(references.glob("*.md")))
    return paths


def validate_shared_runtime_sources() -> None:
    findings: list[str] = []
    for path in shared_runtime_sources():
        raw = path.read_text(encoding="utf-8")
        text = HARNESS_SECTION.sub("", raw)
        unmatched = re.findall(r"<!--\s*harness-specific:[^>]+-->", text, re.IGNORECASE)
        if unmatched:
            findings.append(f"{path.relative_to(ROOT)}: unmatched harness section marker")
        for token in FORBIDDEN_SHARED_MECHANICS:
            if token.lower() in text.lower():
                findings.append(f"{path.relative_to(ROOT)}: {token}")
    if findings:
        raise BuildError("harness mechanics remain in shared runtime sources: " + "; ".join(findings))


def load_binding(path: Path) -> dict:
    with path.open("rb") as handle:
        binding = tomllib.load(handle)
    unknown = set(binding) - EXPECTED_TOP_LEVEL
    missing = EXPECTED_TOP_LEVEL - set(binding)
    if unknown or missing:
        raise BuildError(f"{path}: unknown={sorted(unknown)} missing={sorted(missing)}")
    if binding["version"] != 1:
        raise BuildError(f"{path}: unsupported binding version {binding['version']!r}")
    if binding["harness"] != path.stem:
        raise BuildError(f"{path}: harness must match file name")
    if binding["agent_output_kind"] not in {"markdown", "toml"}:
        raise BuildError(f"{path}: invalid agent_output_kind")
    slots = binding["slots"]
    if set(slots) != EXPECTED_SLOTS:
        raise BuildError(
            f"{path}: binding slots differ: expected={sorted(EXPECTED_SLOTS)} "
            f"actual={sorted(slots)}"
        )
    return binding


def render_template(template: str, slots: dict[str, str], source: Path) -> str:
    used = set(PLACEHOLDER.findall(template))
    if used != set(slots):
        raise BuildError(
            f"{source}: placeholder mismatch: used={sorted(used)} "
            f"provided={sorted(slots)}"
        )
    rendered = PLACEHOLDER.sub(lambda match: slots[match.group(1)].rstrip(), template)
    leftovers = PLACEHOLDER.findall(rendered)
    if leftovers:
        raise BuildError(f"{source}: unresolved placeholders {sorted(set(leftovers))}")
    return rendered.rstrip() + "\n"


def source_hash(*parts: str) -> str:
    digest = hashlib.sha256()
    for part in parts:
        digest.update(part.encode("utf-8"))
        digest.update(b"\0")
    return digest.hexdigest()


def add_markdown_marker(content: str, digest: str) -> str:
    boundary = content.find("\n---\n", 4)
    if boundary < 0:
        raise BuildError("generated Markdown has no closing frontmatter delimiter")
    insertion = boundary + len("\n---\n")
    marker = (
        f"\n<!-- {GENERATED_MARKER} "
        f"{digest} -->\n"
    )
    return content[:insertion] + marker + content[insertion:]


def parse_role(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n") or "\n---\n" not in text[4:]:
        raise BuildError(f"{path}: role source needs simple YAML frontmatter")
    frontmatter, body = text[4:].split("\n---\n", 1)
    fields: dict[str, str] = {}
    for line in frontmatter.splitlines():
        if not line.strip():
            continue
        key, separator, value = line.partition(":")
        if not separator or not value.strip():
            raise BuildError(f"{path}: unsupported frontmatter line {line!r}")
        fields[key.strip()] = value.strip()
    for required in ("name", "description"):
        if required not in fields:
            raise BuildError(f"{path}: missing {required}")
    return fields, body.strip() + "\n"


def codex_role_name(role_name: str) -> str:
    if role_name == "pave-material-reviewer":
        return "pave_init_material_reviewer"
    return "pave_init_" + role_name.replace("-", "_")


def codex_role_preamble(role_name: str) -> str:
    shared = (
        "The parent brief must start with `PAVE_PLUGIN_ROOT: <absolute plugin root>`. "
        "Resolve every `references/...`, `schemas/...`, and `scripts/...` path under "
        "`<PAVE_PLUGIN_ROOT>/skills/pave-init/`. This TOML contains the complete role "
        "contract; do not load or translate a Claude role file at runtime.\n\n"
    )
    special = {
        "forward-tester": (
            "Use the Codex clean-room launch and installation mechanics stated in the "
            "contract below. Inherit the real session model and reasoning defaults.\n\n"
        ),
        "pave-material-reviewer": (
            "Stay on this exact thread for the life of the review gate. Return findings "
            "to the parent and re-check repairs against your own prior findings.\n\n"
        ),
        "skill-builder": (
            "Generate Codex plugin manifests, custom-agent TOML plus explicit installers, "
            "plugin-level hooks, and `codex_exec_script` bindings when the approved plan "
            "requires them. Preserve every approved graph boundary.\n\n"
        ),
    }
    return shared + special.get(role_name, "")


def render_roles(binding: dict) -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    role_settings = binding["roles"]
    sources = sorted(ROLE_SOURCE_DIR.glob("*.md.tmpl"))
    source_names = {path.name.removesuffix(".md.tmpl") for path in sources}
    if source_names != EXPECTED_ROLE_NAMES:
        raise BuildError(
            f"role source set differs: expected={sorted(EXPECTED_ROLE_NAMES)} "
            f"actual={sorted(source_names)}"
        )
    if set(role_settings) != source_names:
        raise BuildError(
            f"{binding['harness']}: role binding mismatch: "
            f"sources={sorted(source_names)} settings={sorted(role_settings)}"
        )
    for source in sources:
        role_name = source.name.removesuffix(".md.tmpl")
        fields, body = parse_role(source)
        if fields["name"] != role_name:
            raise BuildError(f"{source}: name does not match file")
        settings = role_settings[role_name]
        digest = source_hash(
            source.read_text(encoding="utf-8"),
            json.dumps(settings, sort_keys=True),
            binding["harness"],
        )
        runtime = settings.get("runtime")
        if not isinstance(runtime, str) or not runtime.strip():
            raise BuildError(f"{source}: role binding needs non-empty runtime text")
        if binding["agent_output_kind"] == "markdown":
            if set(settings) != {"effort", "model", "runtime", "sandbox_mode"}:
                raise BuildError(
                    f"{source}: Claude role settings must contain model, effort, runtime, and sandbox_mode"
                )
            for key in ("model", "effort"):
                if not isinstance(settings[key], str) or not settings[key]:
                    raise BuildError(f"{source}: Claude role {key} must be a string")
                if settings[key] != "inherit":
                    fields[key] = settings[key]
            frontmatter = "\n".join(
                f"{key}: {value}" for key, value in fields.items()
            )
            output = add_markdown_marker(
                f"---\n{frontmatter}\n---\n\n{runtime.strip()}\n\n{body}",
                digest,
            )
            output_path = ROOT / "agents" / f"{role_name}.md"
        else:
            allowed = {"reasoning_effort", "runtime", "sandbox_mode"}
            if set(settings) != allowed:
                raise BuildError(f"{source}: Codex role settings must be {sorted(allowed)}")
            name = codex_role_name(role_name)
            instructions = (
                codex_role_preamble(role_name)
                + runtime.strip()
                + "\n\n"
                + body
            )
            lines = [
                f"# {GENERATED_MARKER} {digest}",
                f"name = {json.dumps(name)}",
                f"description = {json.dumps(fields['description'])}",
            ]
            if settings["reasoning_effort"] != "inherit":
                lines.append(
                    "model_reasoning_effort = "
                    + json.dumps(settings["reasoning_effort"])
                )
            lines.extend(
                [
                    f"sandbox_mode = {json.dumps(settings['sandbox_mode'])}",
                    f"developer_instructions = {json.dumps(instructions)}",
                    "",
                ]
            )
            output = "\n".join(lines)
            output_path = ROOT / "codex" / "agents" / f"{name}.toml"
        outputs[output_path] = output
    return outputs


def build_outputs() -> dict[Path, str]:
    validate_schema_contract()
    validate_shared_runtime_sources()
    template = SKILL_TEMPLATE.read_text(encoding="utf-8")
    outputs: dict[Path, str] = {}
    binding_paths = sorted(BINDING_DIR.glob("*.toml"))
    actual_binding_files = {path.name for path in binding_paths}
    if actual_binding_files != EXPECTED_BINDING_FILES:
        raise BuildError(
            f"binding files differ: expected={sorted(EXPECTED_BINDING_FILES)} "
            f"actual={sorted(actual_binding_files)}"
        )
    for binding_path in binding_paths:
        binding = load_binding(binding_path)
        skill_path = ROOT / binding["skill_output"]
        if not skill_path.resolve().is_relative_to(ROOT.resolve()):
            raise BuildError(f"{binding_path}: output escapes repository")
        if skill_path in outputs:
            raise BuildError(f"duplicate generated output {skill_path}")
        rendered = render_template(template, binding["slots"], SKILL_TEMPLATE)
        digest = source_hash(template, binding_path.read_text(encoding="utf-8"))
        outputs[skill_path] = add_markdown_marker(rendered, digest)
        for path, content in render_roles(binding).items():
            if path in outputs:
                raise BuildError(f"duplicate generated output {path}")
            outputs[path] = content
    return outputs


def marked_generated_files() -> set[Path]:
    roots = (
        ROOT / "agents",
        ROOT / "codex" / "agents",
        ROOT / "skills" / "pave-init",
        ROOT / "codex" / "skills" / "pave-init",
    )
    marked: set[Path] = set()
    for root in roots:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if not path.is_file():
                continue
            try:
                prefix = path.read_text(encoding="utf-8")[:4096]
            except UnicodeDecodeError:
                continue
            if GENERATED_MARKER in prefix:
                marked.add(path)
    return marked


def check_outputs(outputs: dict[Path, str]) -> int:
    failures = 0
    for path, expected in outputs.items():
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual == expected:
            continue
        failures += 1
        relative = path.relative_to(ROOT)
        print(f"STALE {relative}", file=sys.stderr)
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=str(relative),
            tofile=f"generated/{relative}",
            lineterm="",
        )
        for line in diff:
            print(line, file=sys.stderr)
    for path in sorted(marked_generated_files() - set(outputs)):
        failures += 1
        print(f"ORPHAN {path.relative_to(ROOT)}", file=sys.stderr)
    return failures


def write_outputs(outputs: dict[Path, str]) -> None:
    orphans = marked_generated_files() - set(outputs)
    if orphans:
        listed = ", ".join(str(path.relative_to(ROOT)) for path in sorted(orphans))
        raise BuildError(f"remove orphaned generated outputs before building: {listed}")
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(path.relative_to(ROOT))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build native PAVE Init packages")
    parser.add_argument("--check", action="store_true", help="fail on stale outputs")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        outputs = build_outputs()
        if args.check:
            return 1 if check_outputs(outputs) else 0
        write_outputs(outputs)
        return 0
    except (BuildError, OSError, tomllib.TOMLDecodeError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
